name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'automerge'
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash # or merge, rebase
          MERGE_COMMIT_MESSAGE: "auto-merge: (pull_request_title)"
          MERGE_LABELS: "automerge,!wip"
          UPDATE_LABELS: ""
          UPDATE_METHOD: rebase
